"""updating category model

Revision ID: 230a99a3a2a3
Revises: 83bc08009865
Create Date: 2024-05-16 14:05:21.438003

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '230a99a3a2a3'
down_revision = '83bc08009865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'date')
    op.add_column('stockstoryprompt', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stockstoryprompt', 'category', ['category_id'], ['id'])
    op.drop_column('stockstoryprompt', 'category')
    op.add_column('userstoryprompt', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userstoryprompt', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstoryprompt', type_='foreignkey')
    op.drop_column('userstoryprompt', 'category_id')
    op.add_column('stockstoryprompt', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stockstoryprompt', type_='foreignkey')
    op.drop_column('stockstoryprompt', 'category_id')
    op.add_column('category', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
