"""fix enums for conversation/chat

Revision ID: 3b9af8530cdc
Revises: c61e688b810c
Create Date: 2024-06-15 04:51:16.624415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b9af8530cdc'
down_revision = 'c61e688b810c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('token_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'token_total')
    # ### end Alembic commands ###
