"""added modified_at to UserStoryPrompt

Revision ID: 5101d1870dfb
Revises: 38bca1d62955
Create Date: 2024-06-27 23:20:28.133456

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5101d1870dfb'
down_revision = '38bca1d62955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storysummary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('userstoryprompt', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('userstoryprompt', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstoryprompt', 'modified_at')
    op.drop_column('userstoryprompt', 'created_at')
    op.alter_column('storysummary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
