"""Add column last_name to User model

Revision ID: 61a3d43f11ba
Revises: 61da49d8f352
Create Date: 2024-05-16 05:33:04.014661

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '61a3d43f11ba'
down_revision = '61da49d8f352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
