"""Add title and modified_at to StorySummary

Revision ID: 8035c789ca09
Revises: ab1903954c17
Create Date: 2024-06-16 02:14:15.736063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8035c789ca09'
down_revision = 'ab1903954c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storysummary', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('storysummary', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storysummary', 'modified_at')
    op.drop_column('storysummary', 'title')
    # ### end Alembic commands ###
