"""added contacts table

Revision ID: 9b6f357367d2
Revises: 5101d1870dfb
Create Date: 2024-07-06 12:03:09.085691

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9b6f357367d2'
down_revision = '5101d1870dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('chatmessage_sender_id_fkey', 'chatmessage', type_='foreignkey')
    op.drop_constraint('chatmessage_conversation_id_fkey', 'chatmessage', type_='foreignkey')
    op.create_foreign_key(None, 'chatmessage', 'conversation', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'chatmessage', 'user', ['sender_id'], ['id'])
    op.drop_constraint('conversation_user_id_fkey', 'conversation', type_='foreignkey')
    op.drop_constraint('conversation_user_story_prompt_id_fkey', 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversation', 'userstoryprompt', ['user_story_prompt_id'], ['id'])
    op.drop_constraint('fk_storysummary_user_id', 'storysummary', type_='foreignkey')
    op.drop_constraint('storysummary_conversation_id_fkey', 'storysummary', type_='foreignkey')
    op.create_foreign_key(None, 'storysummary', 'conversation', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'storysummary', 'user', ['user_id'], ['id'])
    op.drop_constraint('userstoryprompt_user_id_fkey', 'userstoryprompt', type_='foreignkey')
    op.create_foreign_key(None, 'userstoryprompt', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstoryprompt', type_='foreignkey')
    op.create_foreign_key('userstoryprompt_user_id_fkey', 'userstoryprompt', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'storysummary', type_='foreignkey')
    op.drop_constraint(None, 'storysummary', type_='foreignkey')
    op.create_foreign_key('storysummary_conversation_id_fkey', 'storysummary', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_storysummary_user_id', 'storysummary', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key('conversation_user_story_prompt_id_fkey', 'conversation', 'userstoryprompt', ['user_story_prompt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversation_user_id_fkey', 'conversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.create_foreign_key('chatmessage_conversation_id_fkey', 'chatmessage', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chatmessage_sender_id_fkey', 'chatmessage', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_table('contact')
    # ### end Alembic commands ###
