"""Added status to Conversation

Revision ID: a6c2f56acf8a
Revises: 98f33f73b147
Create Date: 2024-05-31 22:40:33.911065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'a6c2f56acf8a'
down_revision = '98f33f73b147'
branch_labels = None
depends_on = None

# Define the enum type
conversation_status_enum = ENUM('INACTIVE', 'ACTIVE', 'COMPLETE', name='conversationstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    conversation_status_enum.create(op.get_bind(), checkfirst=True)

    # Add the column to the table
    op.add_column('conversation', sa.Column('status', conversation_status_enum, nullable=False, server_default='INACTIVE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column
    op.drop_column('conversation', 'status')

    # Drop the enum type
    conversation_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
