"""Change the prompt models to using image_url field

Revision ID: b8387de70a69
Revises: a6c2f56acf8a
Create Date: 2024-06-09 03:22:42.270150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8387de70a69'
down_revision = 'a6c2f56acf8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockstoryprompt', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('stockstoryprompt_image_id_fkey', 'stockstoryprompt', type_='foreignkey')
    op.drop_column('stockstoryprompt', 'image_id')
    op.add_column('userstoryprompt', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('userstoryprompt_image_id_fkey', 'userstoryprompt', type_='foreignkey')
    op.drop_column('userstoryprompt', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userstoryprompt', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userstoryprompt_image_id_fkey', 'userstoryprompt', 'image', ['image_id'], ['id'])
    op.drop_column('userstoryprompt', 'image_url')
    op.add_column('stockstoryprompt', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stockstoryprompt_image_id_fkey', 'stockstoryprompt', 'image', ['image_id'], ['id'])
    op.drop_column('stockstoryprompt', 'image_url')
    # ### end Alembic commands ###
